spring.application.name=pos-system
spring.config.import=file:/home/alex/dev/projects/db.properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true